server:
  port: 8090
spring:
  application:
    name: bookCentral
  redis:
    host: 127.0.0.1
    port: 6379
    password:
    jedis:
      pool:
        max-active: 8
        max-wait: -1
        max-idle: 8
        min-idle: 0
    timeout: 5000
# dubbo 相关配置
dubbo:
  application:
    name: bookCentral
    qos-enable: false
    qos-port: 33333
    qos-accept-foreign-ip: false
  registry:
    address: zookeeper://127.0.0.1:2181
